# Combine lotto & weather data, clean it, and EDA.

## Step1: Combine lotto & weather data

In [1]:
import numpy as np
import pandas as pd

In [20]:
weather = pd.read_csv("../dataset/weather_all_20200804T231447.csv")
weather.describe()

,Neihu_pres_hpa,Neihu_temp_cels,Neihu_rh_percent,Songshan_pres_hpa,Songshan_temp_cels,Songshan_rh_percent,Dazhi_pres_hpa,Dazhi_temp_cels,Dazhi_rh_percent,Wenshan_pres_hpa,...,Wenshan_rh_percent,Xizhi_pres_hpa,Xizhi_temp_cels,Xizhi_rh_percent,Shihding_pres_hpa,Shihding_temp_cels,Shihding_rh_percent,Shenkeng_pres_hpa,Shenkeng_temp_cels,Shenkeng_rh_percent
count,1614.000000,1617.000000,1614.000000,1134.000000,1134.000000,1134.000000,1606.000000,1601.000000,1601.000000,1605.000000,...,1599.000000,1615.000000,1615.000000,1613.000000,1605.000000,1601.000000,1569.000000,1060.000000,1060.000000,1055.000000
mean,1010.127138,23.242857,76.473358,1010.131658,23.950529,69.809524,1011.252677,23.532042,75.778888,1009.141558,...,80.913071,1009.481548,22.918266,86.162430,988.607290,20.530294,89.325048,1005.514623,22.030377,85.161137
std,7.038455,5.481157,12.579132,6.846371,5.274670,10.302009,6.947930,5.472397,12.189897,6.888951,...,10.504749,7.050348,5.511996,13.477061,6.411205,5.208167,8.846560,6.869610,5.162815,9.080005
min,975.100000,5.200000,41.000000,983.100000,8.400000,36.000000,976.500000,5.200000,37.000000,974.100000,...,43.000000,976.100000,4.900000,41.000000,955.000000,2.000000,54.000000,978.000000,6.900000,48.000000
25%,1005.100000,19.100000,67.000000,1005.200000,19.900000,62.000000,1006.300000,19.400000,67.000000,1004.200000,...,73.000000,1004.400000,18.700000,76.000000,984.000000,16.700000,84.000000,1000.400000,18.200000,80.000000
50%,1010.000000,23.400000,77.000000,1010.200000,24.000000,70.000000,1011.300000,23.700000,76.000000,1009.100000,...,82.000000,1009.400000,23.100000,90.000000,988.600000,20.800000,91.000000,1006.000000,21.900000,87.000000
75%,1015.400000,27.900000,86.000000,1015.200000,28.700000,78.000000,1016.500000,28.300000,85.000000,1014.200000,...,90.000000,1014.700000,27.600000,99.000000,993.400000,25.000000,97.000000,1010.625000,26.600000,92.000000
max,1033.200000,33.600000,100.000000,1027.300000,33.200000,94.000000,1033.900000,33.600000,100.000000,1031.500000,...,99.000000,1031.800000,33.300000,100.000000,1008.100000,30.400000,100.000000,1022.400000,31.900000,100.000000

In [46]:
weather_summary = weather.describe()
weather_summary.loc["nan"] = weather.isnull().sum()
weather_summary.loc["nan%"] = (weather.isnull().sum()/weather.isnull().count())*100

In [47]:
summary

,Neihu_pres_hpa,Neihu_temp_cels,Neihu_rh_percent,Songshan_pres_hpa,Songshan_temp_cels,Songshan_rh_percent,Dazhi_pres_hpa,Dazhi_temp_cels,Dazhi_rh_percent,Wenshan_pres_hpa,...,Wenshan_rh_percent,Xizhi_pres_hpa,Xizhi_temp_cels,Xizhi_rh_percent,Shihding_pres_hpa,Shihding_temp_cels,Shihding_rh_percent,Shenkeng_pres_hpa,Shenkeng_temp_cels,Shenkeng_rh_percent
count,1614.000000,1617.000000,1614.000000,1134.000000,1134.000000,1134.000000,1606.000000,1601.000000,1601.000000,1605.000000,...,1599.000000,1615.000000,1615.000000,1613.000000,1605.000000,1601.000000,1569.000000,1060.000000,1060.000000,1055.000000
mean,1010.127138,23.242857,76.473358,1010.131658,23.950529,69.809524,1011.252677,23.532042,75.778888,1009.141558,...,80.913071,1009.481548,22.918266,86.162430,988.607290,20.530294,89.325048,1005.514623,22.030377,85.161137
std,7.038455,5.481157,12.579132,6.846371,5.274670,10.302009,6.947930,5.472397,12.189897,6.888951,...,10.504749,7.050348,5.511996,13.477061,6.411205,5.208167,8.846560,6.869610,5.162815,9.080005
min,975.100000,5.200000,41.000000,983.100000,8.400000,36.000000,976.500000,5.200000,37.000000,974.100000,...,43.000000,976.100000,4.900000,41.000000,955.000000,2.000000,54.000000,978.000000,6.900000,48.000000
25%,1005.100000,19.100000,67.000000,1005.200000,19.900000,62.000000,1006.300000,19.400000,67.000000,1004.200000,...,73.000000,1004.400000,18.700000,76.000000,984.000000,16.700000,84.000000,1000.400000,18.200000,80.000000
50%,1010.000000,23.400000,77.000000,1010.200000,24.000000,70.000000,1011.300000,23.700000,76.000000,1009.100000,...,82.000000,1009.400000,23.100000,90.000000,988.600000,20.800000,91.000000,1006.000000,21.900000,87.000000
75%,1015.400000,27.900000,86.000000,1015.200000,28.700000,78.000000,1016.500000,28.300000,85.000000,1014.200000,...,90.000000,1014.700000,27.600000,99.000000,993.400000,25.000000,97.000000,1010.625000,26.600000,92.000000
max,1033.200000,33.600000,100.000000,1027.300000,33.200000,94.000000,1033.900000,33.600000,100.000000,1031.500000,...,99.000000,1031.800000,33.300000,100.000000,1008.100000,30.400000,100.000000,1022.400000,31.900000,100.000000
nan,29.000000,26.000000,29.000000,509.000000,509.000000,509.000000,37.000000,42.000000,42.000000,38.000000,...,44.000000,28.000000,28.000000,30.000000,38.000000,42.000000,74.000000,583.000000,583.000000,588.000000
nan%,1.765064,1.582471,1.765064,30.979915,30.979915,30.979915,2.251978,2.556299,2.556299,2.312842,...,2.678028,1.704200,1.704200,1.825928,2.312842,2.556299,4.503956,35.483871,35.483871,35.788192

In [13]:
with open("../dataset/win_nums_all_20200803T231055.csv", "r", encoding = "Big5") as inFile, open("../dataset/win_nums_all_utf8.csv", "w", encoding = "UTF-8") as outFile:
    outFile.write(inFile.read())

In [15]:
lotto = pd.read_csv("../dataset/win_nums_all_utf8.csv")
lotto.head()

,遊戲名稱,期別,開獎日期,銷售總額,銷售注數,總獎金,獎號1,獎號2,獎號3,獎號4,獎號5,獎號6,特別號
0,大樂透,103000001,2014-01-03,146792850,2935857,80736067,11,18,20,21,35,37,8
1,大樂透,103000002,2014-01-07,132190750,2643815,106318850,1,7,21,25,35,36,39
2,大樂透,103000003,2014-01-10,140617450,2812349,149849635,7,17,19,30,32,37,3
3,大樂透,103000004,2014-01-14,128619400,2572388,70740670,2,11,21,41,45,49,26
4,大樂透,103000005,2014-01-17,141157800,2823156,108354326,13,15,20,26,29,36,37

In [48]:
lotto_summary = lotto.describe()
lotto_summary.loc["nan"] = lotto.isnull().sum()
lotto_summary.loc["nan%"] = (lotto.isnull().sum()/lotto.isnull().count())*100

In [49]:
lotto_summary

,期別,銷售總額,銷售注數,總獎金,獎號1,獎號2,獎號3,獎號4,獎號5,獎號6,特別號
count,7.160000e+02,7.160000e+02,7.160000e+02,7.160000e+02,716.000000,716.000000,716.000000,716.000000,716.000000,716.000000,716.000000
mean,1.058031e+08,1.315611e+08,2.631222e+06,2.007690e+08,7.122905,14.319832,21.678771,28.560056,35.870112,42.893855,24.484637
std,1.902234e+06,7.692533e+07,1.538507e+06,1.558798e+08,5.560247,7.313342,8.022182,7.910197,7.235395,5.596694,14.240533
min,1.030000e+08,6.960865e+07,1.392173e+06,4.382538e+07,1.000000,2.000000,4.000000,7.000000,12.000000,17.000000,1.000000
25%,1.040001e+08,9.179679e+07,1.835936e+06,9.159616e+07,3.000000,9.000000,16.000000,22.750000,31.000000,40.000000,12.000000
50%,1.060000e+08,1.037694e+08,2.075388e+06,1.508259e+08,6.000000,13.000000,21.000000,29.000000,37.000000,44.000000,24.000000
75%,1.070001e+08,1.373668e+08,2.747337e+06,2.524151e+08,10.000000,19.000000,27.000000,34.000000,41.000000,47.000000,38.000000
max,1.090001e+08,6.739330e+08,1.347866e+07,1.070089e+09,31.000000,36.000000,44.000000,47.000000,48.000000,49.000000,49.000000
nan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
nan%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000